### ISSUE TITLE
Determine a Final Name For This Project

### ISSUE THREAD

**Issue by controllerface** [controllerface/CMDR-J#13]
The name EDEPS is not meant to be final, and is just a working title. 

Initially, I was only really going to focus on engineering, but I see now that i'm not going to stop there, and have ideas for more functionality and will eventually support all of the journal events, including exploration. As such, the name should not be "engineering" specific.

In addition, I really don't want to just have an "ED[something]" name, as that's getting a bit played out, IMO. Something that is descriptive  of a "ship board computer" would be better, as the functionality should be pretty general. I see this tool kind of like an augmentation to the ships "OS".

**Comment by LegoDoug** [comment]
Couple of random ideas:

- E-Droid or EDroid
- rEaDout

**Comment by controllerface** [comment]
I have been writing down a few and mostly not liked them after checking again later, but I kind of like CMDR J (pronounced : "Commander J")

**Comment by controllerface** [comment]
It's been a day and I still like CMDR J so just gonna rename everything :-)
