### ISSUE TITLE
(Feature Request) Coriolis Import 

### ISSUE THREAD

**Issue by bsonline** [controllerface/CMDR-J#22]
Paste a link from Coriolis. CMDR J asks if new or current. It then either offers a to do list for a new ship, or builds a comparison and offers a list for that. Bridge the gap from theory crafting to gameplay.

**Comment by controllerface** [comment]
i have not actually done this yet, but I added some more tasks that are step toward this. Namely, you can add purchases of modules as tasks in addition to modifications/specials/etc. 

I did a little bit of poking at a Coriolis.io link with the `code=` param , and at least the first bits of the data with the core and optional modules looks pretty straightforward. There is more data delimited by a `.` that looks a little more complex, and I'm guessing encodes the engineering effects and/or costs. Decoding that would be required for a _full_ import.

**Comment by controllerface** [comment]
Closing older issues to make way for a new version of the project, how the UI works and some of the back-end stuff will be changing. If any of these topics are still interesting after the new version is out will re-open or re-create tickets.
