### ISSUE TITLE
UI :: Inventory Lists

### ISSUE THREAD

**Issue by bsonline** [controllerface/CMDR-J#6]
Reduce padding size to allow more items visible on screen.

**Comment by controllerface** [comment]
can you elaborate on this request? there's very little padding in the UI right now, in fact the drop downs and data are already very close together, so i am assuming you're referencing white-space on these tabs in some place. Maybe a screen cap with some basic notes for suggestions?

**Comment by bsonline** [comment]
Yeah, I literally meant CSS padding. I'll SS it into the channel. It is a
pure vanity item, I couldn't fit everything onto my portrait monitor. :-)

**Comment by controllerface** [comment]
Closing older issues to make way for a new version of the project, how the UI works and some of the back-end stuff will be changing. If any of these topics are still interesting after the new version is out will re-open or re-create tickets.
